spring:
  datasource:
    url: jdbc:h2:./data/db/data.db
    username: sa
    password: 15963PiE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 48000